Sprint 2
RotLenin/middle.messenger.praktikum.yandex pull request #4
Opened 2021-12-12 19:43 UTC by RotLenin

2021-12-13 21:42 UTC, khitrind requested changes
Привет, спасибо за вашу работу, все выглядит очень не плохо, но пока код получился не очень безопасным. Во многих компаниях TS - дефакто продуктовый стандарт и с ним придется разобраться, а где это делать как не в учебном проекте)

Давайте попробуем написать честные типы, сделаем код немного надженее)

2021-12-13 21:42 UTC, khitrind commented on .editorconfig
> +max_line_length = 0
[EOF ](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)
https://eslint.org/docs/rules/eol-last

2021-12-13 21:42 UTC, khitrind commented on .stylelintrc.json
> +}
EOF

2021-12-13 21:42 UTC, khitrind commented on index.ts
> +const PORT = 3000
Хорошо бы иметь возможно прокинуть порт снаружи:

`const port = process.env.PORT || PORT;`

2021-12-13 21:42 UTC, khitrind commented on src/class/controller/Auth.ts
> +  private _form: any;
Почему бы тут не написать честный тип, а не any?

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Auth.ts
> +        .then((res) => res.default)
А зачем это все обернуто в Promise?

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Auth.ts
> +    this._form.querySelector('.accept-btn')
[querySelector](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelector#возвращаемое_значение), может вернуть `null`, тут должна быть проверка на наличие элемента, странно, что TS не подсвечивает это как ошибку

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Chat.ts
> +    id = 1*id;
Тут должны быть честные типы, а не сплошные t`s-ignore`, какой смысл от TS, если код не становится безопаснее?

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Chat.ts
> +    id = 1*id;
Зачем тут id умножается на 1?)

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/DefaultController.ts
> +  // @ts-ignore
Тут должен быть тип, а не ignore

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Profile.ts
> +    this._template = ProfileTemplate;
Это поле можно сразу объявить в теле класса

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Profile.ts
> +    StaticModel.getProfileLocals()
Если уже все обернуто в Promise (я пока если честно не очень понял зачем), то должен быть catch, в котором будет написана логика обработки ошибок

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/controller/Profile.ts
> +    // @ts-ignore
```
const el = this._body.querySelector('.profile-accept-action');

if (el) {
    el.addEventListener('click', this._changeAction);
}
```

а не `ts-ignore`

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/http/HTTPTransport.ts
> +const enum METHODS {
Просто enum

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/http/HTTPTransport.ts
> +  _form = (data: Iobject) => {
Зачем в общем классе работы с сетью, метод для обработки данных формы?

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/http/HTTPTransport.ts
> +        if (this.status >= 200 && this.status < 300) {
Вот это место можно раскомментировать, отличная идея!)

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/http/HTTPTransport.ts
> +      data ? xhr.send(data) : xhr.send();
Тернарные выражения обычно используют, когда нужно возвращаемое значение, в данном случае наглядней получится использовать обычный if

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/view/Block.ts
> +  // @ts-ignore
Зачем тут ts-ignore?

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/view/Block.ts
> +class Block {
props лучше типизировать через [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников.


В общем виде должно получиться, что-то такое:

```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/view/Block.ts
> +  eventBus : any;
Тут тип EventBus, класс может быть типом

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/view/Block.ts
> +    this.eventBus = () => eventBus;
Зачем тут функция, почему нельзя просто:

`this.eventBus = new EventBus();`

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/class/view/Block.ts
> +    console.log(oldProps, newProps);
Хорошо бы в будущем добавить првоерку

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/types/interface/Iobject.ts
> +  [index : string] : any;
Для таких типов есть хэлпер Record:

`Record<string, any>;`

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/utils/inputValidation.ts
> +function nameValidation(name : string, value : string) {
Тут лучше разделить на несколько отдельных функций валидаторов и сложить их в отдельную мапу:

Record<Name, ValidationFunction>;

Так получится немного почище)

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/utils/inputValidation.ts
> +      return value.match('^[-\\w.]+@([A-z0-9][-A-z0-9]+\\.)+[A-z]{2,4}$') !== null;
Люди 10000 лет придумывали [регулярки](https://emailregex.com/) для валидации email, так что такие шутки можно брать готовыми, что бы обработать все кейсы)

2021-12-13 21:42 UTC, DmitryKhitrin commented on src/utils/myLodash.ts
> +export function empty( val : any ) {
val: unknown;

2021-12-14 07:09 UTC, RotLenin commented on .editorconfig
> +max_line_length = 0
Так в .editorconfig уже есть правило на добавление пустой строки в конце файла :
insert_final_newline = true

`insert_final_newline = true`

2021-12-14 16:04 UTC, RotLenin commented on src/utils/inputValidation.ts
> +function nameValidation(name : string, value : string) {
Надеюсь я правильно понял идею с маппером ))))

2021-12-15 07:57 UTC, DmitryKhitrin approved these changes

2022-03-05 13:01 UTC, merged